In [1]:
import pandas as pd

san_antonio = pd.read_csv('/Users/arjunrajesh/Desktop/new2_san_antonio.csv')

In [2]:
import pandas as pd

san_antonio = pd.read_csv('/Users/arjunrajesh/Desktop/new2_san_antonio.csv')
categorical_cols = ['subject_race', 'subject_sex', 'outcome', 'type']

#san_antonio.head()
# One-hot encoding with integer output (1 and 0)
san_antonio_data_encoded = pd.get_dummies(san_antonio, columns=categorical_cols, drop_first=True, dtype=int)

# Verify the first few rows
#print(data_encoded.filter(like='raw_race').head())
print(san_antonio_data_encoded.filter(like='type').head())

   type_vehicular
0               0
1               1
2               1
3               1
4               1

In [3]:
# List your boolean columns
bool_cols = ['arrest_made', 'citation_issued', 'search_conducted']

# Convert them to 1 (True) and 0 (False)
san_antonio_data_encoded[bool_cols] = san_antonio_data_encoded[bool_cols].astype(int)

# Verify the change
print(san_antonio_data_encoded[bool_cols].head())

   arrest_made  citation_issued  search_conducted
0            0                1                 0
1            0                1                 0
2            0                1                 0
3            0                1                 0
4            0                1                 0

In [4]:
san_antonio_data_encoded.head()

,raw_row_number,date,time,location,lat,lng,geocode_source,district,substation,subject_age,...,raw_search_reason,raw_contraband_or_evidence,raw_custodial_arrest_made,subject_race_black,subject_race_hispanic,subject_race_other,subject_race_white,subject_sex_male,outcome_citation,type_vehicular
0,512805|512806,2014-01-01,23:35:00,E COMMERCE,29.419450,-98.456763,GM,4140.0,EAST,38.0,...,NaN,NaN,NaN,0,1,0,0,1,1,0
1,512782|512783,2014-01-01,22:48:00,MERIDA,29.511846,-98.538947,GM,7210.0,PRUE,47.0,...,NaN,NaN,NaN,0,1,0,0,0,1,1
2,512781,2014-01-01,08:30:00,NB STARCREST,29.549645,-98.463889,GM,3130.0,NORTH,27.0,...,NaN,NaN,NaN,0,1,0,0,1,1,1
3,513166|513167|513168,2014-01-01,07:51:00,0000000 IH 35 N,29.352803,-98.529048,GM,6150.0,SOUTH,27.0,...,NaN,NaN,NaN,0,1,0,0,1,1,1
4,512823|512824,2014-01-01,12:27:00,3000 E HOUSTON,29.424226,-98.442586,GM,4160.0,EAST,28.0,...,NaN,NaN,NaN,1,0,0,0,1,1,1

In [5]:
#Drop the subject_race column
san_antonio_data_encoded.drop('raw_race', axis=1, inplace=True, errors='ignore')

#Verify it is gone
print("raw_custodial_arrest_made" in san_antonio_data_encoded.columns)

True

In [28]:
san_antonio_data_encoded.head()

,raw_row_number,date,time,lat,lng,geocode_source,district,substation,subject_age,violation,...,raw_race_I,raw_race_L,raw_race_M,raw_race_O,raw_race_W,raw_race_W|B,raw_race_X,subject_sex_male,outcome_citation,type_vehicular
0,512805|512806,2014-01-01,23:35:00,29.419450,-98.456763,GM,4140.0,EAST,38.0,CROSSING AGAINST PEDESTRIAN CONTROL SIGNAL|PED...,...,0,0,0,0,0,0,0,1,1,0
1,512782|512783,2014-01-01,22:48:00,29.511846,-98.538947,GM,7210.0,PRUE,47.0,DISREGARD STOP SIGN|OPERATING A MOTOR VEHICLE ...,...,0,0,0,0,0,0,0,0,1,1
2,512781,2014-01-01,08:30:00,29.549645,-98.463889,GM,3130.0,NORTH,27.0,OPERATING A MOTOR VEHICLE WITHOUT A VALID LICENSE,...,0,0,0,0,0,0,0,1,1,1
3,513166|513167|513168,2014-01-01,07:51:00,29.352803,-98.529048,GM,6150.0,SOUTH,27.0,SPEEDING-POSTED LIMIT|DRIVING WITHOUT PROOF OF...,...,0,0,0,0,0,0,0,1,1,1
4,512823|512824,2014-01-01,12:27:00,29.424226,-98.442586,GM,4160.0,EAST,28.0,OPERATING A MOTOR VEHICLE WITHOUT A VALID LICE...,...,0,0,0,0,0,0,0,1,1,1

In [40]:
# Drop the subject_race column
san_antonio_data_encoded.drop('raw_custodial_arrest_made', axis=1, inplace=True, errors='ignore')

# Verify it is gone
print("raw_custodial_arrest_made" in san_antonio_data_encoded.columns)

False

In [41]:

# Create new column
san_antonio_data_encoded["extreme_cases"] = ((san_antonio_data_encoded["arrest_made"] == 1) | 
                       (san_antonio_data_encoded["search_conducted"] == 1)).astype(int)

In [43]:
san_antonio_data_encoded.head()

,date,time,lat,lng,geocode_source,district,subject_age,violation,arrest_made,citation_issued,search_conducted,speed,subject_race_black,subject_race_hispanic,subject_race_other,subject_race_white,subject_sex_male,extreme_cases
0,2014-01-01,23:35:00,29.419450,-98.456763,GM,4140.0,38.0,CROSSING AGAINST PEDESTRIAN CONTROL SIGNAL|PED...,0,1,0,NaN,0,1,0,0,1,0
1,2014-01-01,22:48:00,29.511846,-98.538947,GM,7210.0,47.0,DISREGARD STOP SIGN|OPERATING A MOTOR VEHICLE ...,0,1,0,NaN,0,1,0,0,0,0
2,2014-01-01,08:30:00,29.549645,-98.463889,GM,3130.0,27.0,OPERATING A MOTOR VEHICLE WITHOUT A VALID LICENSE,0,1,0,NaN,0,1,0,0,1,0
3,2014-01-01,07:51:00,29.352803,-98.529048,GM,6150.0,27.0,SPEEDING-POSTED LIMIT|DRIVING WITHOUT PROOF OF...,0,1,0,78.0,0,1,0,0,1,0
4,2014-01-01,12:27:00,29.424226,-98.442586,GM,4160.0,28.0,OPERATING A MOTOR VEHICLE WITHOUT A VALID LICE...,0,1,0,NaN,1,0,0,0,1,0

In [44]:
san_antonio_data_encoded.to_csv('san_antonio_cleaned.csv', index=False)